version: '3.8'

services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu
    runtime: nvidia
    tty: true
    stdin_open: true
    volumes:     
      - ./src/model_training:/model_training
      - ./data:/data